### ISSUE TITLE
error: A hook (`sails-eslint`) failed to load!

### ISSUE THREAD

**Issue by ndabAP** [jasancheg/sails-eslint#3]
When I try to lift sails I get this error:

> error: A hook (`sails-eslint`) failed to load!
> error: Error
>     at generateError (/app/backend/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
>     at throwError (/app/backend/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
>     at readDocument (/app/backend/node_modules/js-yaml/lib/js-yaml/loader.js:1508:5)
>     at loadDocuments (/app/backend/node_modules/js-yaml/lib/js-yaml/loader.js:1544:5)
>     at load (/app/backend/node_modules/js-yaml/lib/js-yaml/loader.js:1561:19)
>     at Object.safeLoad (/app/backend/node_modules/js-yaml/lib/js-yaml/loader.js:1579:10)
>     at loadLegacyConfigFile (/app/backend/node_modules/eslint/lib/config/config-file.js:142:21)
>     at loadConfigFile (/app/backend/node_modules/eslint/lib/config/config-file.js:241:22)
>     at Object.load (/app/backend/node_modules/eslint/lib/config/config-file.js:535:18)
>     at loadConfig (/app/backend/node_modules/eslint/lib/config.js:63:33)
>     at getLocalConfig (/app/backend/node_modules/eslint/lib/config.js:130:29)
>     at Config.getConfig (/app/backend/node_modules/eslint/lib/config.js:260:26)
>     at processText (/app/backend/node_modules/eslint/lib/cli-engine.js:224:33)
>     at processFile (/app/backend/node_modules/eslint/lib/cli-engine.js:303:18)
>     at executeOnFile (/app/backend/node_modules/eslint/lib/cli-engine.js:672:25)
>     at fileList.forEach.fileInfo (/app/backend/node_modules/eslint/lib/cli-engine.js:710:13)
>     at Array.forEach (native)
>     at CLIEngine.executeOnFiles (/app/backend/node_modules/eslint/lib/cli-engine.js:709:18)
>     at runLint (/app/backend/node_modules/sails-eslint/index.js:23:20)
>     at /app/backend/node_modules/sails-eslint/index.js:52:7
>     at Array.forEach (native)
>     at processingQueue (/app/backend/node_modules/sails-eslint/index.js:46:8)

**Comment by jasancheg** [comment]
error has been solved!,

I really feel the delay, I had a lot of work and I have not paid enough attention to this repository, the fact is that I made the hook in a moment that I needed it for one of my projects, please excuse. I will be more careful about maintenance.

**Comment by lakshmankashyap** [comment]
today i use sails eslint show error on sails lift like
error: A hook (`sails-eslint`) failed to load!
